/**
 * Streak length to flame tier.
 *
 * This is game logic, not presentation: it decides what a streak has *earned*.
 * It lives in the domain so it is pure and testable, and so the boundaries can
 * be changed — or later generated by the AI layer — without touching the
 * component that draws the flame. The component owns only how a tier looks.
 *
 * Tier boundaries are deliberately front-loaded. The first tier arrives on day
 * one, so a single completion visibly lights the flame; the gaps then widen
 * (6, 7, 16, 30, then open-ended) so the higher tiers stay rare enough to be
 * worth chasing.
 */

export type FlameTier = 0 | 1 | 2 | 3 | 4 | 5

/** Lower bound of each tier, ascending. Index is the tier. */
const TIER_MINIMUMS: readonly number[] = [0, 1, 7, 14, 30, 60]

export const MAX_FLAME_TIER: FlameTier = 5

export function flameTierFor(streak: number): FlameTier {
  // A negative or non-finite streak cannot happen through the app's own code
  // paths, but a corrupted row must not produce a tier the palette has no
  // colour for.
  if (!Number.isFinite(streak) || streak < 1) return 0

  let tier: FlameTier = 0
  for (let i = TIER_MINIMUMS.length - 1; i >= 0; i--) {
    if (streak >= TIER_MINIMUMS[i]!) {
      tier = i as FlameTier
      break
    }
  }
  return tier
}

/** Days remaining until the next tier, or `null` at the top tier. */
export function daysToNextTier(streak: number): number | null {
  const tier = flameTierFor(streak)
  if (tier >= MAX_FLAME_TIER) return null
  const next = TIER_MINIMUMS[tier + 1]!
  return Math.max(0, next - Math.max(0, Math.floor(streak)))
}

/** The streak range a tier covers, for labelling. `null` upper bound = open. */
export function tierRange(tier: FlameTier): { from: number; to: number | null } {
  const from = TIER_MINIMUMS[tier]!
  const nextMin = TIER_MINIMUMS[tier + 1]
  return { from, to: nextMin === undefined ? null : nextMin - 1 }
}
